[workspace]

members = [
    "rust/ast",
    "rust/parser",
    "rust/js_backend",
    "rust/type_checker",
    "rust/typed_ast",
]

[workspace.dependencies]
nom = "7.1.3"
nom_locate = "4.0.0"

[toolchain]
channel = "1.66.0"
components = ["rustfmt", "clippy", "cargo-cranky"]
