[workspace]

members = [
    "rust/ast",
    "rust/parser",
    "rust/js_backend",
    "rust/type_checker",
    "rust/typed_ast",
]

[toolchain]
channel = "1.66.0"
components = ["rustfmt", "clippy", "cargo-cranky"]
