deny = [
    "clippy::pedantic",
    "clippy::nursery",
    "clippy::perf",
    "clippy::unwrap_used",
    "clippy::expect_used",
    "unsafe_code",

]

warn = [
]

allow = [
    "clippy::module_name_repetitions",
    "clippy::missing-errors-doc",
    "clippy::struct-excessive-bools",
]